using System;
using R3;
using UI.General.Binder;
using UI.General.Elements.Popup;
using UI.ProjectSpecific.Model;

namespace UI.ProjectSpecific.ViewModel
{
    public partial class LosePopup : UIPopupT<LosePopupData>
    {
        [Bindable]
        private ReactiveProperty<bool> isRewardedVideoAvailable = new(false);

        private Action onRestartLevelClicked;
        private Action onRestoreLevelClicked;
        private Action onMoveToLobbyClicked;

        public override void Initialize(LosePopupData data)
        {
            isRewardedVideoAvailable.Value = data.IsRestoreLevelRewardVideoReady;

            onRestartLevelClicked = data.OnRestartLevelClicked;
            onRestoreLevelClicked = data.OnRestoreLevelClicked;
            onMoveToLobbyClicked = data.OnMoveToLobbyClicked;
        }

        [Bindable]
        public void OnRestartButtonClicked()
        {
            onRestartLevelClicked?.Invoke();
            Close();
        }

        [Bindable]
        public void OnWatchButtonClicked()
        {
            onRestoreLevelClicked?.Invoke();
            Close();
        }

        [Bindable]
        public void OnMoveToLobbyClicked()
        {
            onMoveToLobbyClicked?.Invoke();
            Close();
        }

        #region AutoGenerated

        protected override void GatherObservableProperties()
        {
            // Used by the source generator to register observable properties.
        }

        protected override void GatherBindableMethods()
        {
            // Used by the source generator to register bindable methods.
        }

        #endregion
    }
}