using System;
using General.Injection;
using R3;
using UI.General.Binder;
using UI.General.Elements.Widget;
using UI.ProjectSpecific.Model;
using VContainer;

namespace UI.ProjectSpecific.ViewModel
{
    public partial class PlayerHealthWidget : UIWidget, IInjectableComponent
    {
        // Can be Serialized in Inspector with SerializeFieldAttribute and SerializableReactiveProperty
        [Bindable]
        private ReactiveProperty<bool> isHealthInfinity = new();

        [Bindable]
        private ReactiveProperty<string> currentHealthText = new();

        [Bindable]
        private Subject<Unit> onHealthDecreased = new();

        [Bindable]
        private Subject<Unit> onHealthIncreased = new();

        private IDisposable subscription;
        private int previousHealth;

        [Inject]
        public void Construct(IPlayerHealth playerHealthModel)
        {
            var bag = Disposable.CreateBuilder();
            previousHealth = playerHealthModel.CurrentHealth.CurrentValue;

            playerHealthModel.CurrentHealth.Subscribe(value =>
            {
                currentHealthText.Value = value.ToString();

                if (value < previousHealth)
                {
                    onHealthDecreased.OnNext(Unit.Default);
                }
                else if (value > previousHealth)
                {
                    onHealthIncreased.OnNext(Unit.Default);
                }

                previousHealth = value;
            }).AddTo(ref bag);

            playerHealthModel.IsHealthInfinity.Subscribe(value => { isHealthInfinity.Value = value; }).AddTo(ref bag);

            subscription = bag.Build();
        }

        private void OnDestroy()
        {
            subscription.Dispose();
        }

#region AutoGenerated
        protected override void GatherObservableProperties()
        {
            // Used by the source generator to register observable properties.
        }

        protected override void GatherBindableMethods()
        {
            // Used by the source generator to register bindable methods.
        }
#endregion
    }
}